/// Model representing an upcycling idea generated by AI
class IdeaModel {
  final String title;
  final String description;
  final List<String> materials;
  final List<String> steps;
  final String? generatedImageUrl;
  final DateTime timestamp;

  IdeaModel({
    required this.title,
    required this.description,
    required this.materials,
    required this.steps,
    this.generatedImageUrl,
    required this.timestamp,
  });

  /// Convert model to JSON for local storage
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'description': description,
      'materials': materials,
      'steps': steps,
      'generatedImageUrl': generatedImageUrl,
      'timestamp': timestamp.toIso8601String(),
    };
  }

  /// Create model from JSON
  factory IdeaModel.fromJson(Map<String, dynamic> json) {
    return IdeaModel(
      title: json['title'] ?? 'Creative Idea',
      description: json['description'] ?? 'Transform your item into something new.',
      materials: List<String>.from(json['materials'] ?? []),
      steps: List<String>.from(json['steps'] ?? []),
      generatedImageUrl: json['generatedImageUrl'],
      timestamp: DateTime.parse(json['timestamp'] ?? DateTime.now().toIso8601String()),
    );
  }
}